### ISSUE TITLE
[Epic] RGBv1 Core Release

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/devcalls#26]
- [x] `amplify` & `amplify_derive` v1.0 release
- [ ] LNP/BP Core Library 0.1.0 release
- [ ] RGB Node release
- [ ] docker containers release
- [ ] reference wallet release
- [ ] write RGB spec v1
- [ ] complete all related LNPBP standards
