### ISSUE TITLE
[Epic] RGB LN v0.1

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/devcalls#27]
- [ ] LNP/BP Core Library 0.2 release
- [ ] RGB Node 0.2 release
- [ ] LNP Node 0.1 release
- [ ] updates to docker containers
