### ISSUE TITLE
[Epic] RGBv1 (final release)

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/devcalls#28]
- [ ] LNP/BP Library v1.0
- [ ] RGB Core v1.0
- [ ] RGB LN v1
- [ ] RGB Node v1 (with integration pack)
- [ ] LNP Node v1 (with integration pack)
- [ ] Docker containers

Planned date: 1st February 2021
