### ISSUE TITLE
Dev call 2020-Apr-22

### ISSUE THREAD

**Issue by UkolovaOlga** [LNP-BP/devcalls#9]
# Dev call 2020-Apr-22

### Newly developed
*(contributions from @dr-orlovsky, @alekos, @Kixunil)*
* Wallets
    - [x] Graph verification: https://github.com/LNP-BP/rust-lnpbp/pull/28
    - [x] Wallet/integration-specific functions: https://github.com/LNP-BP/rust-lnpbp/pull/37
    - [x] RGB SDK: https://github.com/rgb-org/rgb-sdk
    - [x] Kaleidoscope: https://github.com/rgb-org/kaleidoscope
* General dev
    - [x] Blind seals: https://github.com/LNP-BP/rust-lnpbp/pull/41
    - [x] Support for Liquid and custom networks: https://github.com/LNP-BP/rust-lnpbp/pull/40
    - [x] Universal data serialization for ZMQ API: https://github.com/LNP-BP/rust-lnpbp/pull/33
* Nodes
    - [x] Signet-related docker containers
         * bitcoind fork: https://hub.docker.com/layers/lnpbp/bitcoind/signet/images/sha256-4cda51a60a249f3eef17cc7361e170f62793c511ecb9708b8874d867f34c8dd8?context=explore
         * electrs fork: https://hub.docker.com/layers/lnpbp/electrs/signet/images/sha256-a8dbba65445714226ae63c8df4811fc00ce1de1125c809363ac03d0c6b701beb?context=explore
         * docker-compose for Signet: https://github.com/LNP-BP/docker/blob/master/signet/docker-compose.yml
    - [x] BP node progress: TX query service -> BP node https://github.com/LNP-BP/bp-node

### Protocol design
- [x] Single asset LN channel design considerations and questions: https://github.com/LNP-BP/LNPBPs/issues/25
- [x] UDP Hole punching: proposal by @prdn
- [x] LNPBP-4: use of simplified/more efficient mechanics: https://github.com/LNP-BP/LNPBPs/issues/19
- [x] RGB Contract Standards based on Schema (compatibility for asset types using slight schema modifications, solving the same problem like "ERC-20")
- [x] Wallet support: API and library specialization proposed by @prdn

### Current challenges & issues need help
- [ ] Ubuntu secp256k1 / secp256k1-zkp conflict
- [ ] Rust-lightning/bitcoin compatibility: https://github.com/rust-bitcoin/rust-lightning/issues/578
- [ ] WASM-to-native complex API considerations
- [ ] Bitcoin transaction signature problem: https://github.com/rgb-org/kaleidoscope/blob/00453d11e4b3525d120daa3772ed64311d21d2bb/src/runtime.rs#L520-L541 this code does not produce correct signature
- [ ] CA compatibility: https://github.com/LNP-BP/rust-lnpbp/issues/38
- [ ] Confidential proofs code verification & optimization

### Contributions to external projects
- [ ] Electrs: support for new rust-bitcoin: https://github.com/romanz/electrs/pull/238 and https://github.com/romanz/electrs/pull/240
- [ ] Electrs: support for Signet: https://github.com/romanz/electrs/pull/239

### Next tasks:
- [ ] Proof serialization for wallet storage and P2P protocol @afilini 
- [ ] Finalization of RGB Contracts library @dr-orlovsky
- [ ] WASM/FFI bindings for RGB Contracts library @afilini 
- [ ] BP node API for RGB-specific queries @dr-orlovsky 
- [ ] LNP P2P protocol (BOLT-8/1 based) @dr-orlovsky 
- [ ] Refactoring (simplification) of LNP/BP Core library @dr-orlovsky

## Roadmap updates
- [ ] May 1: Command-line wallet to issue and transfer RGB fungible assets over Signet goes public
- [ ] May 7: Start of test integration work with @prdn:
    * Set of server nodes with core functionality (bp-node, lnp-node, rgb-node)
    * RGB libraries in their fungible part
    * WASM/C FFI bindings
- [ ] June 1: Hybrid c-lightning/lnp-node able to make direct payments with RGB assets

## Non-development updates:
- [x] Moving to a weekly call schedule
- [ ] RGB-specific parts like command-line wallet, SDK and contract type standards & implementation placed on https://github.com/rgb-org
- [ ] Defining RGB terminology in short tech intro: https://github.com/rgb-org/rgb-org.github.io/blob/master/index.md
